### PR TITLE
Use "apply" block function for Builder

### PR DESCRIPTION
**Pull request by Cleymax**
Use [apply](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/apply.html) function block for DotenvBuilder

### CODE REVIEW

**Comment by cdimascio** [comment]
@Cleymax thanks, behavior-wise, this change looks effectively the same. is the thinking to make this code a bit more idiomatic to Kotlin?

**Comment by Cleymax** [comment]
Yes, that's it.

**Review by Vinetos — APPROVED** [review]
It's ok !
apply is a good idea

**Review by cdimascio — APPROVED** [review]

**Comment by cdimascio** [comment]
@all-contributors add @Cleymax for code

**Comment by Cleymax** [comment]
Thank you 🙂

**Pull request merged**
