### PR TITLE
Add a `.list()` method to `Dotenv`

### PR DESCRIPTION
**Pull request by pwoolcoc**
Currently, I am writing a gradle plugin for .env files, and it would be nice to be able to iterate over the list of variables that were defined in the .env file

### CODE REVIEW

**Comment by cdimascio** [comment]
@pwoolcoc thanks! 
this is good idea. will have a look

**Comment by pwoolcoc** [comment]
@cdimascio I see you added and then commented out an iterator for it -- are you planning on un-commenting that at some point? that would work for me just as well as a list would, tbh

**Comment by cdimascio** [comment]
@pwoolcoc yes. I commented it out as it needed some work. The types weren't working out well on the Java side. I believe I have it resolved now

All in all, I borrowed many of your ideas
The PR is [here](https://github.com/cdimascio/java-dotenv/pull/21/files), feel free to comment. I'm happy to make adjustments. I believe it now meets your needs.

The change is available in v4.1.0. It should make it to MavenCentral within ~24hours

**Comment by cdimascio** [comment]
@pwoolcoc FYI: If you want to try it out before it makes it to MavenCentral you can get it from JCenter with the following:

If you need it more quickly you can resolve to JCenter with the following:
**Gradle**

```
repositories {
    maven {
        url  "https://dl.bintray.com/cdimascio/maven" 
    }
}
```

**Maven**
`settings.xml` file
```
<?xml version="1.0" encoding="UTF-8" ?>
<settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd'
          xmlns='http://maven.apache.org/SETTINGS/1.0.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    
    <profiles>
        <profile>
            <repositories>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-cdimascio-maven</id>
                    <name>bintray</name>
                    <url>https://dl.bintray.com/cdimascio/maven</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-cdimascio-maven</id>
                    <name>bintray-plugins</name>
                    <url>https://dl.bintray.com/cdimascio/maven</url>
                </pluginRepository>
            </pluginRepositories>
            <id>bintray</id>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>bintray</activeProfile>
    </activeProfiles>
</settings>
```

**Comment by cdimascio** [comment]
@pwoolcoc would love to checkout your gradle plugin once its ready to go. sounds interesting!

**Comment by cdimascio** [comment]
There's also a usage blurb in the [documentation](https://github.com/cdimascio/java-dotenv#iterate-over-environment-variables)

**Comment by pwoolcoc** [comment]
this looks great, thanks! this will work perfectly for me :) I'll let you know when i have published my plugin

**Comment by cdimascio** [comment]
@all-contributors please add @pwoolcoc for ideas

**Pull request closed without merging**
