### PR TITLE
Update iterate syntax in README

### PR DESCRIPTION
**Pull request by mjduijn**
Dotenv in version 4.1.0 has no method entries, instead it implements iterator itself

### CODE REVIEW

**Comment by cdimascio** [comment]
@mjduijn I had accidentally pushed a version with dotenv implementing iterator. I thought I had properly removed and it republished with `entries`. I wonder if it could be stuck in the maven or gradle cache

would you mind trying to clear your cache and reinstall dotenv 4.1.0:
For maven, you can do the following (assuming .m2 is in your home dir):
`rm -rf ~/.m2/repository/io/github/cdimascio/java-dotenv/`

Apologies for the confusion. I may consider posting a new version in case this doesn't solve the problem. It could be that you as well as others have this version installed

**Comment by mjduijn** [comment]
I'm using Bazel which doesn't usually suffer from these kinds of issues.
I've tried removing the jars locally, no change.
The sha1s of the downloaded jar and sourcejar are the same as on [maven](http://central.maven.org/maven2/io/github/cdimascio/java-dotenv/4.1.0/)

Not sure how mavencentral works, but could it be a caching issue on their side?

**Comment by cdimascio** [comment]
@mjduijn thanks a lot. it could be. i'll release a new major version to be safe. don't want to break folks.
thanks a lot for this ticket

**Comment by cdimascio** [comment]
@mjduijn a new v5.0.0 release is available. The v5 API matches the README. It usually takes a day or for the artifact to propagate to MavenCentral, however you can get it immediately [here on JCenter](https://bintray.com/cdimascio/maven/java-dotenv) by following the instructions on 'Set Me Up'.

**Comment by mjduijn** [comment]
That's great!
Thank you for the quick response.

**Pull request closed without merging**
